"use strict";
exports.__esModule = true;
var ProductService_1 = require("./ProductService");
var Product_1 = require("./Product");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getById(2);
var p = new Product_1.Product();
p.id = 2;
p.name = 'Asus';
p.category = 'Computer';
p.price = 2000;
result = _productService.saveProduct(p);
result = _productService.getProducts();
console.log(result);
